name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      run: echo "${{secrets.DOCKER_PAT}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    - name: Create Short SHA
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Building the Image
      run: |
       docker build -t "${{secrets.DOCKER_USERNAME}}"/terminal_portfolio:latest .
       docker tag "${{secrets.DOCKER_USERNAME}}"/terminal_portfolio:latest "${{secrets.DOCKER_USERNAME}}"/terminal_portfolio:${{env.SHORT_SHA}}

    - name: Push the image to Docker Hub
      run: |
        docker push "${{secrets.DOCKER_USERNAME}}"/terminal_portfolio:latest
        docker push ${{ secrets.DOCKER_USERNAME }}terminal_portfolio:${{ env.SHORT_SHA }}
